version: 2

builds:
  - id: fleetdeck-amd64
    main: .
    binary: fleetdeck
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/fleetdeck/fleetdeck/cmd.Version={{.Version}}
      - -X github.com/fleetdeck/fleetdeck/cmd.Commit={{.Commit}}
      - -X github.com/fleetdeck/fleetdeck/cmd.BuildDate={{.Date}}
      - -X github.com/fleetdeck/fleetdeck/cmd.ReleaseRepository={{ .Env.GITHUB_REPOSITORY }}
  - id: fleetdeck-arm64
    main: .
    binary: fleetdeck
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X github.com/fleetdeck/fleetdeck/cmd.Version={{.Version}}
      - -X github.com/fleetdeck/fleetdeck/cmd.Commit={{.Commit}}
      - -X github.com/fleetdeck/fleetdeck/cmd.BuildDate={{.Date}}
      - -X github.com/fleetdeck/fleetdeck/cmd.ReleaseRepository={{ .Env.GITHUB_REPOSITORY }}

archives:
  - id: default
    ids:
      - fleetdeck-amd64
      - fleetdeck-arm64
    formats:
      - tar.gz
    name_template: "fleetdeck_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - INSTALL*
  - id: raw
    ids:
      - fleetdeck-amd64
      - fleetdeck-arm64
    formats:
      - binary
    name_template: "fleetdeck-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

signs:
  - id: checksum-keyless
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
